export const about_us = "https://drive.google.com/uc?export=view&id=19wXhCnURWT5E6O3tEMeQSW_sfqr7eyfD"

export const building_metal_structures = "https://drive.google.com/uc?export=view&id=1PoTw7NdWblVC6xi7pD4NJgHnB4UwIty1"
export const building_metal_structures_small = "https://drive.google.com/uc?export=view&id=1YGNrSlTMuvPn8TMpZkiXSOD3AB61w3hc"
export const metal_products = "https://drive.google.com/uc?export=view&id=1ejQgmebmZqjb9qR0EoKXNAT5eTlSBHpP"
export const metal_products_small = "https://drive.google.com/uc?export=view&id=1QG5i6IuddyTf7vfPj72Ux1V54hmfNjS6"
export const unusual_metal_structures = "https://drive.google.com/uc?export=view&id=1KygsncoCXwq9XDv0FzOLlhFjtDLLlrA3"
export const unusual_metal_structures_small = "https://drive.google.com/uc?export=view&id=1yIkYKrKvGBPoUKJN7KN7ZRL2dWdNY4fK"

export const metal_cover_1 = "https://drive.google.com/uc?export=view&id=1eZfzK3mNAdmictrT8bQBq-TSKd7SDaJS"
export const metal_cover_medium_1 = "https://drive.google.com/uc?export=view&id=1SVrPgRE-Fxa6BAbb4tjTT1SN4TpsbYQH"
export const metal_cover_small_1 = "https://drive.google.com/uc?export=view&id=1udf4FqhxKTY-9qrM4kfOhHT4Q-EjKcln"
export const metal_cover_2 = "https://drive.google.com/uc?export=view&id=1sEUzWXE8_egilpLOGkftHSxjuA0A2zrc"
export const metal_cover_medium_2 = "https://drive.google.com/uc?export=view&id=1-adj5j7gzmwGP3iR7jlXo0PsHc5ebbii"
export const metal_cover_small_2 = "https://drive.google.com/uc?export=view&id=1HXLzayunDeUxSz-_92A_IwQePIQwlxMq"
export const armature_1 = "https://drive.google.com/uc?export=view&id=1oWb9r6PADrg-9dzDMdGBCStWqiGog1ld"
export const armature_medium_1 = "https://drive.google.com/uc?export=view&id=1LnRBelS4wl3FkOPLCbgNzuxuZpuTKZQe"
export const armature_small_1 = "https://drive.google.com/uc?export=view&id=1yR-34L9LevcjdoxA4KBiyV-Zfv_U8D0h"
export const armature_2 = "https://drive.google.com/uc?export=view&id=1tT8u0RD1SkVj8QG7gjsysrYOp0QOq4Jw"
export const armature_medium_2 = "https://drive.google.com/uc?export=view&id=1sKY6pVgflumeiEByWe3-GeL66zosCGBy"
export const armature_small_2 = "https://drive.google.com/uc?export=view&id=1ckx7aK1_zGJNty34DABB7XJlC1zRmAH7"
export const laser_cutting_of_metal_1 = "https://drive.google.com/uc?export=view&id=1vWoOkOFEcbhFQ1NCC3DXzg2iU57VL2if"
export const laser_cutting_of_metal_medium_1 = "https://drive.google.com/uc?export=view&id=1W3wAAHHOcBPsExfZoFQ08YFdmLy6GcK2"
export const laser_cutting_of_metal_small_1 = "https://drive.google.com/uc?export=view&id=1Xw3p0FLK6ULgBC-51M6RfP8BThN-3_iX"
export const laser_cutting_of_metal_2 = "https://drive.google.com/uc?export=view&id=1w-gcmq6hLwOUqJ_eIdAfG722KtNA62AA"
export const laser_cutting_of_metal_medium_2 = "https://drive.google.com/uc?export=view&id=1CmJSPb1sq_EO94TtwwlnEeSJyR5Hqs1Y"
export const laser_cutting_of_metal_small_2 = "https://drive.google.com/uc?export=view&id=1-EmpvvsiqnaBwve1B004_Q4_T2tev2co"

export const reviews_dark = "https://drive.google.com/uc?export=view&id=1PhnMDhtgFGBcbmSlNvO2DqodqGq9XTe5"
export const reviews_light = "https://drive.google.com/uc?export=view&id=1-o7NJpGBAyl8wkFu7fyKJcQrHrkf50c9"
export const reviews_dark_medium = "https://drive.google.com/uc?export=view&id=1QSmxkT3YTSD9QZCLlMfffE4HvIO9P-k_"
export const reviews_light_medium = "https://drive.google.com/uc?export=view&id=1N-U5vmXv9qYkp5VAoiuS4Eza6aAmB_Pr"
export const reviews_dark_small = "https://drive.google.com/uc?export=view&id=1Y7U9cuIPTxV2AewQSsCPEKMPiHnkYwkm"
export const reviews_light_small = "https://drive.google.com/uc?export=view&id=1c8RSlgp37fqM6437FQByylH2mHjOD2MK"