export const bending_of_reinforcement_first = "https://drive.google.com/uc?export=view&id=1EAalOeI5DI1isBvciqotmDUX94PwsScn"
export const bending_of_reinforcement_first_small = "https://drive.google.com/uc?export=view&id=1WlT9cNZZZkQ4fWMM3lS0XSVwCJhG4V7D"
export const bending_of_reinforcement_second = "https://drive.google.com/uc?export=view&id=1iWquxOgMl3p8WvjWprNV_ze_hVhDupuu"
export const bending_of_reinforcement_second_small = "https://drive.google.com/uc?export=view&id=1_ahooAaq9sWB7yveeTFtiIpVWIsPMMQC"
export const bending_of_reinforcement_third = "https://drive.google.com/uc?export=view&id=1GhcbzktDqxSmoqA-2GTABB8hvAIu7cKu"
export const bending_of_reinforcement_third_medium = "https://drive.google.com/uc?export=view&id=1IdRLdMX8k-I8HtVk5q6CZX8R-2Tn_kGj"
export const bending_of_reinforcement_third_small = "https://drive.google.com/uc?export=view&id=13nLXAGwu2yYvZKqKVr2CVfmJXZS4urA2"
export const bending_of_reinforcement_fourth = "https://drive.google.com/uc?export=view&id=1lr4S213K4gOsA1TPYQnE-_l0ykiYsT2H"
export const bending_of_reinforcement_fourth_medium = "https://drive.google.com/uc?export=view&id=1FnaPyHTe45r2wiFJNJq26Wc6zsG2seNI"
export const bending_of_reinforcement_fourth_small = "https://drive.google.com/uc?export=view&id=1MFE3G6wpdz4WN_JZFJdhRqLUdNZKZRpP"

export const plasma_cutting_of_metal_first = "https://drive.google.com/uc?export=view&id=17OGHL1bq3zkD3wqgnWmyMYUY99zteInp"
export const plasma_cutting_of_metal_first_small = "https://drive.google.com/uc?export=view&id=1HiRyO_-F8g3H2gUfpPzp2XQmUzDIaVqZ"
export const plasma_cutting_of_metal_second = "https://drive.google.com/uc?export=view&id=1b8Nur--lxgGurmpImGGeEtyrtmeXQPzY"
export const plasma_cutting_of_metal_second_small = "https://drive.google.com/uc?export=view&id=174f2QBMVj-R_SEQilfKr7inxihtNn8XI"
export const plasma_cutting_of_metal_third = "https://drive.google.com/uc?export=view&id=1ufl7RZ02m-yHaT-zjs89jwezZYkqzkl3"
export const plasma_cutting_of_metal_third_small = "https://drive.google.com/uc?export=view&id=1pS-7KAZbMswvM-LEEKw_EG2N0Ey2DLgV"
export const plasma_cutting_of_metal_fourth = "https://drive.google.com/uc?export=view&id=1g-o6eVa8xc5gFMLlq9T6tHL7q3Sxzumz"
export const plasma_cutting_of_metal_fourth_small = "https://drive.google.com/uc?export=view&id=1O3zqvSFut06tU3-krDUqugW-QF8ubCSI"

export const lathe_works_first = "https://drive.google.com/uc?export=view&id=1V0g7-Lv4HAaEZGaKzLKZI32rdYcodtwX"
export const lathe_works_first_medium = "https://drive.google.com/uc?export=view&id=1O_bOWfsTmMLhe06uNIq4yAG8DwDc2J0a"
export const lathe_works_first_small = "https://drive.google.com/uc?export=view&id=1RZeW9AXrPt8gtzH99OjJBaFDUJA1vxbu"
export const lathe_works_second = "https://drive.google.com/uc?export=view&id=16xLPqNzBVx5xCSZ9zKpyhvhp2n1obZJS"
export const lathe_works_second_medium = "https://drive.google.com/uc?export=view&id=1lIZz0WyxNDHjEESr1iCqTXTkce2nAp6F"
export const lathe_works_second_small = "https://drive.google.com/uc?export=view&id=1NpkYA_R2ZkM11Ph7GQX7Z9wFx5x-zXUE"

export const metal_cutting_a_bandsaw_first = "https://drive.google.com/uc?export=view&id=1O5d6wTC5fBRx9dXUEhhwb4VEcT652Cvc"
export const metal_cutting_a_bandsaw_second = "https://drive.google.com/uc?export=view&id=1Ji5zZqhmXlE59Z9zfw6EKgcpI33ouQ3q"
export const metal_cutting_a_bandsaw_third = "https://drive.google.com/uc?export=view&id=1VqulGlXE3pXAAon7sVstCmoLpgaasGnh"
export const metal_cutting_a_bandsaw_fourth = "https://drive.google.com/uc?export=view&id=1G2GjHss_sjhPLNZhn9JLfuxlVzTsLpAH"